---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: debian-7
    driver_config:
      image: debian:7.8
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
  - name: centos-6
    driver_config:
      image: centos:centos6

suites:
  - name: default
    run_list:
      - recipe[smoke::default]
    attributes:
      td_agent:
        includes: true
  - name: td-agent-1.x
    run_list:
      - recipe[smoke::default]
    attributes:
      td_agent:
        version: 1
    excludes:
      - debian-7
      - ubuntu-14.04
