---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: debian7-chef12
    driver_config:
      platform: debian
      image: debian:7.8
      require_chef_omnibus: 12.21.3
  - name: ubuntu12-chef12
    driver_config:
      platform: ubuntu
      image: ubuntu:12.04
      require_chef_omnibus: 12.21.3
  - name: ubuntu14-chef12
    driver_config:
      platform: ubuntu
      image: ubuntu:14.04
      require_chef_omnibus: 12.21.3
  - name: centos6-chef12
    driver_config:
      platform: centos
      image: centos:centos6
      require_chef_omnibus: 12.21.3

suites:
  - name: default
    run_list:
      - recipe[smoke::default]
    attributes:
      td_agent:
        includes: true
  - name: td-agent1
    run_list:
      - recipe[smoke::default]
    attributes:
      td_agent:
        version: 1
    excludes:
      - debian7-chef12
      - ubuntu14-chef12
