sudo: required
dist: trusty
language: ruby

services:
  - docker

cache:
  bundler: true
  directories:
    - /var/lib/docker

env:
  matrix:
    - TEST_INSTANCE=default-debian7-chef12
    - TEST_INSTANCE=default-ubuntu12-chef12
    - TEST_INSTANCE=default-ubuntu14-chef12
    - TEST_INSTANCE=default-centos6-chef12
    - TEST_INSTANCE=td-agent1-ubuntu12-chef12
    - TEST_INSTANCE=td-agent1-centos6-chef12

script:
  - |
    set -ex -o pipefail
    bundle exec kitchen converge "${TEST_INSTANCE}"
